 export const qouotes = [
    'stand proud',
    'opened up his domain',
    'he said',
    'are you',
    "you're strong",
    "because you are",
    "i'm you",
    "or are you",
    "The one who left it all behind!",
    "And his overwhelming intensity!!",
    "because",
    "with this treasure i summon",
    "?",
    "the finger simply answered",
    "nah i'd win",
    "nah i'd lose",
    "stand proud, you're strong",
    "i'm into girls like jeniffer lawrence, nice to meet you!",
    "are you the honored one cause you're nah i'd win, or are you nah i'd win cause you're the honored one"
]